version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: web_postgres
    restart: always
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitor
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./BackEnd
    container_name: web_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: monitor
      DB_PASS: monitor
      DB_NAME: monitor

  nginx:
    image: nginx:latest
    container_name: web_nginx
    ports:
      - "80:80"
    volumes:
      - ./BackEnd/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./FrontEnd:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  postgres_data: